# DNSé˜²æ³„éœ²ç‰ˆæœ¬
# å¿…è¯»ï¼ï¼ï¼
# æ³¨æ„è§„åˆ™åœ¨æ»¡è¶³è‡ªå·±éœ€æ±‚æƒ…å†µä¸‹ï¼Œå°½é‡åšåˆ°ç²¾ç®€ï¼Œä¸è¦è¿‡åº¦å¤æ‚ï¼Œä»¥å…å½±å“æ€§èƒ½ã€‚
# è·‘è£¸æ ¸ç”¨æˆ·è¯·è‡ªè¡Œå»æ‰ä¸‹æ–¹æ§åˆ¶é¢æ¿æ¨¡å—çš„æ³¨é‡Šã€‚
# æœºåœºè®¢é˜…
proxy-providers:
  å°‘æ•°æ´¾:
    url: "https://x-sub-sllnramygq.cn-shanghai.fcapp.run/x/a37037c14e24c96392d96ad2d8edeeb9"
    type: http
    interval: 0
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
    proxy: ğŸ¯ ç›´è¿
  è‰¯å¿ƒäº‘:
    url: "https://liangxin.xyz/api/v1/liangxin?OwO=6aad819e5a2aea1bd9c12acc58e07699"
    type: http
    interval: 0
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
    proxy: ğŸ¯ ç›´è¿
# èŠ‚ç‚¹ä¿¡æ¯
proxies:
  - {name: ğŸ¯ ç›´è¿, type: direct}

# å…¨å±€é…ç½® 
mixed-port: 7890
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: warning
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# å—…æ¢ï¼ˆfakeipä¸‹å…¶å®å¯ä»¥ä¸ç”¨å—…æ¢ï¼‰
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
    - "+.apple.com"
    - "+.microsoft.com"
    - "+.windows.com"
    - "+.qlogo.cn"
    - "+.weixin.com"
    - "+.lan"
    - "+.local"
  force-domain:
    - "+.google.com"               # å¼ºåˆ¶å—…æ¢è¿™äº›åŸŸå
    - "+.youtube.com"
    - "+.netflix.com"
  skip-dst-address:
    - "192.168.0.0/16"             # è·³è¿‡ç§æœ‰åœ°å€
    - "10.0.0.0/8"
    - "172.16.0.0/12"

# å…¥ç«™
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  #device: nikki    #ä½¿ç”¨nikkiï¼Œæ··å…¥å…¨éƒ¨ä¸ä¿®æ”¹çš„æƒ…å†µï¼Œå¼€å¯æ¥å£æŒ‡å®šä¸ºnikki
  #ä½¿ç”¨ä»…å†…æ ¸è‡ªè¡Œä¿®æ”¹ä¸‹é¢ä¸‰é¡¹ä¸ºtrue
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false

# DNSæ¨¡å—
dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:53
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  default-nameserver:
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver:
    - https://8.8.8.8/dns-query#RULES
    - https://1.1.1.1/dns-query#RULES
  fake-ip-filter:
    - "rule-set:fakeipfilter_domain"
 
# å‡ºç«™ç­–ç•¥ï¼Œæ ¹æ®è‡ªå·±æƒ…å†µè°ƒæ•´æ¯ä¸ªç­–ç•¥é‡Œåˆ†ç»„æ’åºï¼Œå¢åˆ éƒ½å¯ä»¥ï¼Œæ¯”å¦‚æŠŠç¾å›½è‡ªåŠ¨æ”¾åˆ°ç¬¬ä¸€ä¸ªï¼Œæ¯”å¦‚åˆ é™¤é¦™æ¸¯æ•…è½¬ï¼Œæ³¨æ„åˆ«æ¼æ‰è¡¨æƒ…é€—å·ç­‰ã€‚
# å¦‚æœç›¸åº”åˆ†ç»„æ²¡æœ‰ç­›é€‰åˆ°å¯¹åº”çš„å›½å®¶ï¼Œè¯·æ ¹æ®è‡ªå·±èŠ‚ç‚¹åå­—è°ƒæ•´ç­›é€‰å…³é”®å­—ã€‚
# æ²¡æœ‰å†ä½¿ç”¨é”šç‚¹ï¼Œæ˜¯è€ƒè™‘å¾ˆå¤šæ–°æ‰‹ä¿®æ”¹éš¾åº¦ï¼Œè¿™æ ·æ–°æ‰‹ä¿®æ”¹æŸä¸ªåˆ†ç»„æ›´å®¹æ˜“äº›ã€‚
proxy-groups:
  - {name: ğŸš€ é»˜è®¤ä»£ç†, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ”° èŠ‚ç‚¹é€‰æ‹©, ğŸ¯ ç›´è¿, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ”° èŠ‚ç‚¹é€‰æ‹©, ğŸ¯ ç›´è¿, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨]}
  - {name: ğŸ€ è°·æ­ŒæœåŠ¡, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ”° èŠ‚ç‚¹é€‰æ‹©, ğŸ¯ ç›´è¿, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨]}
  - {name: â“‚ï¸ å¾®è½¯æœåŠ¡, type: select, proxies: [ğŸ¯ ç›´è¿,â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ”° èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨]}
  - {name: ğŸ è‹¹æœæœåŠ¡, type: select, proxies: [ğŸ¯ ç›´è¿,â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ”° èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨]}
  - {name: ğŸ“² ç”µæŠ¥ä¿¡æ¯, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ”° èŠ‚ç‚¹é€‰æ‹©, ğŸ¯ ç›´è¿, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨]}
  - {name: ğŸŒ å›½å¤–åª’ä½“, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ”° èŠ‚ç‚¹é€‰æ‹©, ğŸ¯ ç›´è¿, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨]}
  - {name: ğŸŒ STEAMæ¸¸æˆ, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ”° èŠ‚ç‚¹é€‰æ‹©, ğŸ¯ ç›´è¿, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨]}
  - {name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©, type: select, include-all: true}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 30, interval: 600, filter: "^((?!(ğŸ¯ ç›´è¿)).)*$"}
  - {name: â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 30, interval: 600, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 30, interval: 600, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$"}
  - {name: â™»ï¸ ç‹®åŸè‡ªåŠ¨, type: url-test, include-all: true, tolerance: 30, interval: 600, filter: "(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore))^((?!(æ¸¯|å°|éŸ©|æ—¥|ç¾)).)*$"}
  - {name: â™»ï¸ ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 30, interval: 600, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}


# è§„åˆ™åŒ¹é…
rules:
  - RULE-SET,private_ip,ğŸ¯ ç›´è¿,no-resolve
  - RULE-SET,private_domain,ğŸ¯ ç›´è¿
  - RULE-SET,proxylite,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,youtube_domain,ğŸ€ è°·æ­ŒæœåŠ¡
  - RULE-SET,github_domain,ğŸ€ è°·æ­ŒæœåŠ¡
  - RULE-SET,google_domain,ğŸ€ è°·æ­ŒæœåŠ¡
  - RULE-SET,onedrive_domain,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,microsoft_domain,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,steam_domain,ğŸŒ STEAMæ¸¸æˆ
  - RULE-SET,steam@cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,apple_domain,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,telegram_domain,ğŸ“² ç”µæŠ¥ä¿¡æ¯
  - RULE-SET,ai,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,tiktok_domain,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,netflix_domain,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,paypal_domain,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,speedtest_domain,ğŸ¯ ç›´è¿
  
  - RULE-SET,apple_ip,ğŸ è‹¹æœæœåŠ¡,no-resolve
  - RULE-SET,google_ip,ğŸ€ è°·æ­ŒæœåŠ¡,no-resolve
  - RULE-SET,netflix_ip,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - RULE-SET,telegram_ip,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,cn_ip,ğŸ¯ ç›´è¿,no-resolve
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

  # è§„åˆ™é›†
## typeï¼šå¯é€‰http/file/inline  behaviorï¼šå¯é€‰domain/ipcidr/classical formatï¼šå¯é€‰yaml/text/mrs
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  fakeipfilter_domain: {<<: *domain, url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"}
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list"}
  steam_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam.mrs"}
  steam@cn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam@cn.mrs"}
  ai: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}

  private_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  apple_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}
